Repository SENG499-Company-4/Frontend, pull requests merged in 2022-07, with the labels that each got.

#81 Added section select to schedule generate page
  app/src/components/pages/ScheduleGenerate.tsx
  app/src/components/shared/interfaces/ScheduleGenerate.interfaces.ts
Labels: Feature, UI

#84 Scheduler Route Parameters
  app/src/components/pages/ProfessorProfile.tsx
  app/src/components/pages/ProfessorsList.tsx
  app/src/components/pages/ScheduleTimetable.tsx
  app/src/utils/utils.ts
  app/tsconfig.json
Labels: Feature

#105 Feature/88
  app/package-lock.json
  app/package.json
  app/public/manifest.json
  app/src/App.tsx
  app/src/api/Mutations.ts
  app/src/api/Queries.ts
  app/src/components/molecules/HeaderButton.tsx
  app/src/components/molecules/HeaderMenu.tsx
  app/src/components/molecules/SemesterSelector.tsx
  app/src/components/molecules/TermOptions.tsx
  app/src/components/molecules/TimetableFilter.tsx
  app/src/components/organisms/Appointment.tsx
  app/src/components/organisms/Header.tsx
  app/src/components/organisms/ScheduleControl.tsx
  app/src/components/organisms/SurveyClassQuestion.tsx
  app/src/components/organisms/SurveyForm.tsx
  app/src/components/pages/Login.tsx
  app/src/components/pages/PlugAndPlay.tsx
  app/src/components/pages/ProfessorProfile.tsx
  app/src/components/pages/ProfessorsList.tsx
  app/src/components/pages/ScheduleGenerate.tsx
  app/src/components/pages/ScheduleList.tsx
  app/src/components/pages/ScheduleManage.tsx
  app/src/components/pages/ScheduleTimetable.tsx
  app/src/components/pages/Survey.tsx
  app/src/components/styles/scheduler.css
  app/src/components/styles/styles.ts
  app/src/constants/surveyForm.constants.ts
  app/src/contexts/ErrorContext.tsx
  app/src/contexts/LoadingContext.tsx
  app/src/contexts/TermSelectorContext.tsx
  app/src/contexts/UserContext.tsx
  app/src/data/clean.json
  app/src/index.tsx
  app/src/interfaces/ScheduleGenerate.interfaces.ts
  app/src/interfaces/scheduleGenerate.interfaces.ts
  app/src/interfaces/scheduleManage.interfaces.ts
  app/src/interfaces/timetable.interfaces.ts
  app/src/interfaces/user.interfaces.ts
  app/src/router/AppRouter.tsx
  app/src/tests/Appointment.test.tsx
  app/src/tests/utils.test.tsx
  app/src/types/api.types.ts
  app/src/utils/utils.ts
Labels: Epic
